language: go
go:
  - 1.6
# Use container infrastructure.
sudo: false
env: GO15VENDOREXPERIMENT=1
cache:
  directories:
    - node_modules
    - google-cloud-sdk
before_install:
  # Decrypt service account key file.
  - openssl aes-256-cbc -K $encrypted_5d88bc4a54f7_key -iv $encrypted_5d88bc4a54f7_iv -in ellies-pad/tools/cmd/deploy/key.json.enc -out ellies-pad/tools/cmd/deploy/key.json -d
  # Only deploy on master.
  - if test "$TRAVIS_PULL_REQUEST" = false && test "$TRAVIS_BRANCH" = master; then export DEPLOY=true; fi
  # Only build and test the API if it has changed, or we should deploy.
  - if test "$DEPLOY" || test $(git rev-list --count "$TRAVIS_COMMIT_RANGE" -- ellies-pad/api) -ne 0 || test $(git rev-list --count "$TRAVIS_COMMIT_RANGE" -- vendor) -ne 0; then export API=true; fi
  # Only build and test the web app if it has changed, or we should deploy.
  - if test "$DEPLOY" || test $(git rev-list --count "$TRAVIS_COMMIT_RANGE" -- ellies-pad/web) -ne 0; then export WEB=true; fi
  # If we need to build and test the web app, install a newer version of node.
  - if test "$WEB"; then nvm install 7.9.0; fi
  # If we need to build and test the web app, install yarn.
  - if test "$WEB"; then npm install --global yarn; fi
install:
  - |
    if test "$API"
    then
      if test ! -e google-cloud-sdk/bin/gcloud
      then
        # Download the Google Cloud SDK if we didn't have it in the cache.
        wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-119.0.0-linux-x86_64.tar.gz &&
        tar xzf google-cloud-sdk-119.0.0-linux-x86_64.tar.gz
      fi
      export PATH="$PWD/google-cloud-sdk/bin:$PATH"
    fi
  - |
    if test "$WEB"
    then
      yarn install
    fi
script:
  - if test "$API"; then go test ./ellies-pad/api; fi
  - |
    if test "$WEB"
    then (
      cd ellies-pad/web
      yarn run test
    ) fi
after_success: |
  if test "$DEPLOY"
  then
    # Deploy the API and web app.
    go run ellies-pad/tools/cmd/deploy/deploy.go -keyFile ellies-pad/tools/cmd/deploy/key.json
  fi
