application: ellies-pad
version: 1
runtime: go
api_version: go1

handlers:
- url: /.well-known/acme-challenge/pQ6P0e6Ur2iidBqq9jKGHjOzR4zvTVCxtJGrNyktRvs
  static_files: ssl
  upload: ssl
- url: /graphql
  script: _go_app
  login: admin
- url: /static
  static_dir: static
  login: admin
- url: /.*
  static_files: static/index.html
  upload: static/index.html
  login: admin
