application: ellies-pad
version: 1
runtime: go
api_version: go1

handlers:
- url: /graphql
  script: _go_app
  login: admin
  secure: always
- url: /static
  static_dir: static
  login: admin
  secure: always
- url: /.*
  static_files: static/index.html
  upload: static/index.html
  login: admin
  secure: always
